site_name: Programming and Software Notes

nav:

    - Documentation:
        - MkDocs: 'documentation/mkdocs.md'
        - Sphinx: 'documentation/sphinx.md'
        - Doxygen: 'documentation/doxygen.md'
        - LaTeX: 'documentation/latex.md'
    - GMT:
        - GMT5: 'gmt/gmt5.md'
        - GMT6: 'gmt/gmt6.md'
        - pyGMT: 'gmt/pygmt.md'
    - Seismology:
        - Data requests: 'seismology/data_requests.md'
        - SEISAN: 'seismology/seisan.md'
        - ObsPy: 'seismology/obspy.md'
    - Programming:
        - CUDA: 'programming/cuda.md'
    - Tools:
        - Docker: 'tools/docker.md'
        - CMake: 'tools/cmake.md'
        - Git: 'tools/git.md'
        - tmux: 'tools/tmux.md'
        - vim: 'tools/vim.md'
    - Unix:
        - Admin: 'unix/admin.md'
        - Commands: 'unix/commands.md'
        - Dotfiles: 'unix/dotfiles.md'
        - Installation: 'unix/installation.md'
    - macOS:
        - Monterrey installation: 'macos/monterrey.md'
        - MacPorts: 'macos/macports.md'
        - Python installation: 'macos/python.md'
        - Tips: 'macos/tips.md'
        - Installation: 'macos/installation.md'
        - Admin: 'macos/admin.md'

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

theme: readthedocs
