site_name: Programming and Software Notes

nav:

    - Home: 'index.md'
    - MkDocs: 'mkdocs.md'


extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

theme: readthedocs
